### ISSUE TITLE
Don't show system tray icon when built without --enable-appindicator

### ISSUE THREAD

**Issue by ThanosApostolou** [mate-desktop/mate-polkit#33]
When mate-polkit is configured without `--enable-appindicator` (like the arch package) then every time is runs, it shows an ugly icon on system tray which immediately disappears if you click on it. I've made a bug report on the arch package in order to add `--enable-appindicator` option, but I believe that the current behaviour isn't appropriate.

In my opinion, when `--enable-appindicator` is not used, then it shouldn't show any icon on system tray at all, because otherwise it's ugly and confusing for users. I don't know if this can be easily implemented. Tell me what you think.

**Comment by raveit65** [comment]
The broken a-tray applet icon i could fixed with using an icon from icon-theme instead of a GtkStock icon.
https://github.com/mate-desktop/mate-polkit/commit/448a62596d81b108935a6b6eea1db20b548bf5ae
In general  using libindicator is better than using deprecate GtkStatusIcon, but using libindicator change the behaviour of the na-tray applet.
The applet don't close any more if you close the application where it was used for, and it seems to stay open the whole session.
I am not sure if i want to build it with --enable-appindicator for fedora.

**Comment by ThanosApostolou** [comment]
Hmm I see usage of appindicators is controversial and I've noticed that both arch and fedora package maintainers prefer not to use them... Anyway, thx for the quick fix. I tested **mate-polkit** 1.18.1 and the icon works without --enable-appindicator. I flagged the arch package **out-of-date** in order to notify the maintainers too.

Feel free to close this.
